# 데이터사이언스 개론 ssl.py & JNB 과제
> 202003613 글로벌스포츠산업학부 최진원

## 기존 소스 코드

In [1]:
# 학번: 202003613 / 학과: 글로벌스포츠산업학부 / 이름: 최진원
# Node 클래스 정의
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# LinkedList 클래스 정의
class LinkedList:
    # 초기화 메소드
    def __init__(self):
        dummy = Node("dummy")
        self.head = dummy
        self.tail = dummy
        self.current = None
        self.before = None
        self.num_of_data = 0

    # append 메소드 (insert - 맨 뒤에 노드 추가, tail과 node의 next, 데이터 개수 변경)
    def append(self, data):
        new_node = Node(data)
        self.tail.next = new_node
        self.tail = new_node
        self.num_of_data += 1

    # delete 메소드 (delete - current 노드 삭제, 인접 노드의 current, next 변경, 데이터 개수 변경)
    def delete(self):
        pop_data = self.current.data
        if self.current is self.tail:
            self.tail = self.before
            # 중요 : current가 next가 아닌 before로 변경된다.
            self.before.next = self.current.next
            self.current = self.before
            self.num_of_data -= 1
        return pop_data

    # first 메소드 (search1 - 맨 앞의 노드 검색, before, current 변경)
    def first(self):
        # 데이터가 없는 경우 첫번째 노드도 없기 때문에 None 리턴
        if self.num_of_data == 0:
            return None
        self.before = self.head
        self.current = self.head.next
        return self.current.data

    # next 메소드 (search2 - current 노드의 다음 노드 검색, 이전에 first 메소드가 한번은 실행되어야 함)
    def next(self):
        if self.current.next == None:
            return None
        self.before = self.current
        self.current = self.current.next
        return self.current.data

    # size 메소드
    def size(self):
        return self.num_of_data

## 추가 함수

### traverse_all()
* -> head부터 tail까지 각 노드를 순차적으로 탐색하며 각 노드의 data를 출력함

In [2]:
def traverse_all(self):
    node = self.head.next
    result = "head"
    # 본 함수는 리스트의 첫 번째 노드부터 시작한다.
    # result 변수를 "head" 문자열로 초기화하고, 이 변수는 각 노드의 데이터 값을 문자열로 변환한 후 이전 노드의 문자열과 함께 연결하여 최종 문자열을 만드는 데 사용된다.
    
    while node != None:
        result += " -> " + "(" + str(node.data) + ")"
        node = node.next
    # 노드가 None이면, 즉 노드의 tail에 다다를 때까지, 각 노드의 데이터 값을 문자열로 변환하여 result 변수에 추가하고, 다음 노드로 이동하는 작업을 반복한다.
    
    result += " -> null"
    print(result)
    # result 변수에 " -> null" 문자열을 추가하여 리스트의 끝을 표시한다.
    # 마지막으로, 리스트의 모든 노드를 출력한다.

### insert_at(position, new_data)
* -> 리스트의 주어진 위치에 new_data를 삽입함

In [3]:
def insert_at(self, position, new_data):
    if position <= 0:
        print("error")
        return
    # position이 0보다 작거나 같으면 error 메시지를 출력하고 함수를 종료한다.
    
    elif position > self.num_of_data:
        self.append(new_data)
    # position이 리스트의 현재 노드 개수보다 크다면, append 함수를 호출하여 리스트의 맨 뒤에 노드를 추가한다.
    
    else:
        new_node = Node(new_data)
        node = self.head
    # 그렇지 않으면, 삽입하려는 위치까지 이동하여 새 노드를 삽입한다
    # 먼저, new_node 객체를 생성하고, node 변수를 리스트의 head 노드로 초기화한다.
    
        for i in range(position - 1):
            node = node.next
        # 그리고 position의 이전 노드까지 node를 이동시킨다.
        
        new_node.next = node.next
        node.next = new_node
        self.num_of_data += 1
        # 그 다음, new_node.next를 현재 노드의 다음 노드로 설정하고, node.next를 new_node로 설정한다.
        # 마지막으로, num_of_data 변수를 1 증가시켜서 리스트의 총 노드 개수를 업데이트한다.

### remove(key)
* -> 리스트의 원소 가운데 key 값과 일치하는 원소를 모두 삭제하고, 리스트를 수정함

In [4]:
def remove(self, key):
    node = self.head.next
    before_node = self.head
    index = 1
    remove_indexes = []
    # 본 함수는 리스트의 첫 번째 노드부터 시작한다.
    # node 변수는 현재 노드를 가리키고, before_node 변수는 이전 노드를 가리킨다.
    # index 변수는 현재 노드의 인덱스, 즉 위치를 저장한다.
    # removed_indexes 리스트는 삭제된 노드의 인덱스를 저장한다.
    
    while node != None:
    # 노드가 None이면, 즉 노드의 tail에 다다를 때까지 반복한다. 

        if node.data == key:
            before_node.next = node.next
        # 현재 노드 값이 key 값과 일치하면, 삭제하고자 하는 노드를 기준으로 이전 노드의 next 값을 다음의 노드로 설정하여 노드를 삭제한다.
            
            if node is self.tail:
                self.tail = before_node
            # 이 때, 삭제된 노드가 리스트의 마지막 노드인 경우에는 tail 변수를 이전 노드로 업데이트한다.
            
            print(f"{index}번째 원소를 삭제합니다.")
            removed_indexes.append(index)
            # 현재 노드 값과 key 값이 일치하여 노드를 삭제하였으므로, index 값을 이용하여 몇 번째 원소를 삭제하였는지 출력한다.
            # 삭제한 노드의 인덱스를 removed_indexes 리스트에 추가한다.
            
        else:
            before_node = node
        # 현재 노드 값과 key 값이 일치하지 않으면, 이전 노드를 현재 노드로 업데이트한다.
            
        node = node.next
        index += 1
        # 현재 노드에서 다음 노드로 넘어갈 때 index 값을 1 증가시킨다.
        
    if not removed_indexes: 
        print("해당하는 원소가 없습니다.")
    # 모든 노드에 대한 검사가 끝난 후, 만약 removed_indexes 리스트에 값이 없다면, 즉 삭제된 노드가 없는 경우, "해당하는 원소가 없습니다."라는 메시지를 출력한다.

## 코드 실행 결과

In [5]:
# 학번: 202003613 / 학과: 글로벌스포츠산업학부 / 이름: 최진원
# Node 클래스 정의
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# LinkedList 클래스 정의
class LinkedList:
    # 초기화 메소드
    def __init__(self):
        dummy = Node("dummy")
        self.head = dummy
        self.tail = dummy
        self.current = None
        self.before = None
        self.num_of_data = 0

    # append 메소드 (insert - 맨 뒤에 노드 추가, tail과 node의 next, 데이터 개수 변경)
    def append(self, data):
        new_node = Node(data)
        self.tail.next = new_node
        self.tail = new_node
        self.num_of_data += 1

    # delete 메소드 (delete - current 노드 삭제, 인접 노드의 current, next 변경, 데이터 개수 변경)
    def delete(self):
        pop_data = self.current.data
        if self.current is self.tail:
            self.tail = self.before
            # 중요 : current가 next가 아닌 before로 변경된다.
            self.before.next = self.current.next
            self.current = self.before
            self.num_of_data -= 1
        return pop_data

    # first 메소드 (search1 - 맨 앞의 노드 검색, before, current 변경)
    def first(self):
        # 데이터가 없는 경우 첫번째 노드도 없기 때문에 None 리턴
        if self.num_of_data == 0:
            return None
        self.before = self.head
        self.current = self.head.next
        return self.current.data

    # next 메소드 (search2 - current 노드의 다음 노드 검색, 이전에 first 메소드가 한번은 실행되어야 함)
    def next(self):
        if self.current.next == None:
            return None
        self.before = self.current
        self.current = self.current.next
        return self.current.data

    # size 메소드
    def size(self):
        return self.num_of_data

    # traverse_all 메소드 (head부터 tail까지 각 노드를 순차적으로 탐색하며 각 노드의 data를 출력함)
    def traverse_all(self):
        node = self.head.next
        result = "head"
        while node != None:
            result += " -> " + "(" + str(node.data) + ")"
            node = node.next
        result += " -> null"
        print(result)

    # insert_at 메소드 (리스트의 주어진 위치에 new_data를 삽입함)
    def insert_at(self, position, new_data):
        if position <= 0:
            print("error")
            return
        elif position > self.num_of_data:
            self.append(new_data)
        else:
            new_node = Node(new_data)
            node = self.head
            for i in range(position - 1):
                node = node.next
            new_node.next = node.next
            node.next = new_node
            self.num_of_data += 1

    # remove 메소드 (리스트의 원소 가운데 key값과 일치하는 원소를 모두 삭제하고, 리스트를 수정함)
    def remove(self, key):
        node = self.head.next
        before_node = self.head
        index = 1
        removed_indexes = []
        while node != None:
            if node.data == key:
                before_node.next = node.next
                if node is self.tail:
                    self.tail = before_node
                print(f"{index}번째 원소를 삭제합니다.")
                removed_indexes.append(index)
            else:
                before_node = node
            node = node.next
            index += 1
        if not removed_indexes:
            print("해당하는 원소가 없습니다.")

linked_list = LinkedList()

linked_list.append(100)
linked_list.append(72)
linked_list.append(325)
linked_list.traverse_all()
print()

linked_list.insert_at(0, 150)
linked_list.insert_at(2, 150)
linked_list.traverse_all()
linked_list.insert_at(10, 150)
linked_list.traverse_all()
print()

linked_list.remove(75)
linked_list.traverse_all()
linked_list.remove(150)
linked_list.traverse_all()

head -> (100) -> (72) -> (325) -> null

error
head -> (100) -> (150) -> (72) -> (325) -> null
head -> (100) -> (150) -> (72) -> (325) -> (150) -> null

해당하는 원소가 없습니다.
head -> (100) -> (150) -> (72) -> (325) -> (150) -> null
2번째 원소를 삭제합니다.
5번째 원소를 삭제합니다.
head -> (100) -> (72) -> (325) -> null


### traverse_all()
* 앞선 코드 실행 결과를 참고하였을 때, 정상적으로 작동함을 알 수 있음.  
* traverse_all() 함수를 실행했을 때, 100, 72, 325의 노드 값으로 이루어져 있는 리스트를 "head -> (100) -> (72) -> (325) -> null"로 출력하였는데, 이는 head부터 tail까지 각 노드를 순차적으로 탐색하며 각 노드의 data를 출력하고자 하는 목적에 부합함.

### insert_at(position, new_data)
* 앞선 코드 실행 결과를 참고하였을 때, 정상적으로 작동함을 알 수 있음. 
* insert_at(position, new_data) 함수를 실행했을 때, 100, 72, 325의 노드 값으로 이루어져 있는 리스트에서 먼저 실행한 예문의 경우 150이라는 값을 0의 위치에 넣었는데, 첫 원소의 위치를 1로 설정하였기 때문에 0 이하의 값을 입력했을 경우 error가 출력되는 조건에 따라 error가 출력됨.  
* 다음 예문의 경우 마찬가지로 150이라는 값을 2의 위치에 넣었을 때 "head -> (100) -> (150) -> (72) -> (325) -> null"로 출력되는데, 이를 통해 150이라는 값이 2의 위치에 입력되었음을 확인할 수 있고, 따라서 리스트의 주어진 위치에 new_data를 삽입하고자 하는 목적에 부합함.  
* 원소가 4개임을 고려하였을 때, 이보다 더 큰 값인 10의 위치에 150이라는 값을 넣는 예문의 결과가 "head -> (100) -> (150) -> (72) -> (325) -> (150) -> null"로 출력되는데, 만일 입력한 값이 현재 리스트의 크기보다 크면 맨 마지막에 new_data를 삽입한다는 조건 또한 부합함을 알 수 있음.

### remove(key)
* 앞선 코드 실행 결과를 참고하였을 때, 정상적으로 작동함을 알 수 있음.  
* remove(key) 함수를 실행했을 때, 100, 150, 72, 325, 1000의 노드 값으로 이루어져 있는 리스트에서 먼저 실행한 예문의 경우 75라는 값을 삭제하고자 하는데, 리스트에 해당 값이 존재하지 않기 때문에 "해당하는 원소가 없습니다."라는 문구가 출력되고, traverse_all() 함수를 통해 리스트의 변화가 없음을 확인할 수 있음.  
* 다음 예문의 경우 150이라는 값을 삭제하고자 했을 때 "head -> (100) -> (150) -> (72) -> (325) -> (150) -> null"의 리스트에서 150이 2번째, 5번째 위치에 있기 때문에 "2번째 원소를 삭제합니다." "5번째 원소를 삭제합니다."라는 메시지가 출력되고, traverse_all() 함수를 통해 리스트를 추력했을 때 "head -> (100) -> (72) -> (325) -> null"로 출력되는데, 입력한 150의 값이 정상적으로 삭제됐음을 알 수 있음.